/**
 * @jest-environment node
 */
import jwt from 'jsonwebtoken';

const TEST_SECRET = 'test-jwt-secret-for-middleware';
const COOKIE_NAME = 'meme_radar_session';

process.env.JWT_SECRET = TEST_SECRET;
process.env.SESSION_COOKIE_NAME = COOKIE_NAME;

// Mock NextResponse since next/server isn't fully available in node test env
const mockRedirect = jest.fn().mockImplementation((url: URL) => ({
  status: 307,
  headers: new Headers({ location: url.toString() }),
}));

const mockNext = jest.fn().mockImplementation(() => ({
  status: 200,
  headers: new Headers(),
}));

jest.mock('next/server', () => ({
  NextRequest: jest.requireActual('next/server').NextRequest,
  NextResponse: {
    redirect: (...args: unknown[]) => mockRedirect(...args),
    next: (...args: unknown[]) => mockNext(...args),
  },
}));

import { middleware } from '../../src/middleware';
import { NextRequest } from 'next/server';

function createRequest(path: string, token?: string): NextRequest {
  const url = `http://localhost:3000${path}`;
  const req = new NextRequest(url);
  if (token) {
    req.cookies.set(COOKIE_NAME, token);
  }
  return req;
}

function generateValidToken(userId: string, expiresIn = '7d'): string {
  return jwt.sign({ userId }, TEST_SECRET, { expiresIn });
}

function generateExpiredToken(userId: string): string {
  return jwt.sign({ userId }, TEST_SECRET, { expiresIn: '0s' });
}

function generateTokenWithWrongSecret(userId: string): string {
  return jwt.sign({ userId }, 'wrong-secret-key', { expiresIn: '7d' });
}

function generateTokenWithoutUserId(): string {
  return jwt.sign({ someOtherField: 'value' }, TEST_SECRET, { expiresIn: '7d' });
}

describe('middleware — JWT signature verification', () => {
  beforeEach(() => {
    mockRedirect.mockClear();
    mockNext.mockClear();
  });

  describe('valid tokens', () => {
    it('allows access with a valid JWT token', async () => {
      const token = generateValidToken('user-123');
      const req = createRequest('/dashboard', token);
      await middleware(req);

      expect(mockNext).toHaveBeenCalled();
      expect(mockRedirect).not.toHaveBeenCalled();
    });

    it('accepts tokens generated by jsonwebtoken library (HS256 compatibility)', async () => {
      const token = generateValidToken('user-abc-456');
      const req = createRequest('/stock/GME', token);
      await middleware(req);

      expect(mockNext).toHaveBeenCalled();
      expect(mockRedirect).not.toHaveBeenCalled();
    });
  });

  describe('missing tokens', () => {
    it('redirects to /login when no token cookie exists', async () => {
      const req = createRequest('/dashboard');
      await middleware(req);

      expect(mockRedirect).toHaveBeenCalled();
      const redirectUrl = mockRedirect.mock.calls[0][0] as URL;
      expect(redirectUrl.pathname).toBe('/login');
    });
  });

  describe('signature verification (security-critical)', () => {
    it('rejects tokens signed with a different secret (forged JWT)', async () => {
      const forgedToken = generateTokenWithWrongSecret('user-123');
      const req = createRequest('/dashboard', forgedToken);
      await middleware(req);

      expect(mockRedirect).toHaveBeenCalled();
      expect(mockNext).not.toHaveBeenCalled();
    });

    it('rejects manually crafted tokens with tampered payload', async () => {
      const validToken = generateValidToken('user-123');
      const parts = validToken.split('.');
      const tamperedPayload = Buffer.from(
        JSON.stringify({ userId: 'admin-hacker', exp: Math.floor(Date.now() / 1000) + 3600 })
      ).toString('base64url');
      const tamperedToken = `${parts[0]}.${tamperedPayload}.${parts[2]}`;

      const req = createRequest('/dashboard', tamperedToken);
      await middleware(req);

      expect(mockRedirect).toHaveBeenCalled();
      expect(mockNext).not.toHaveBeenCalled();
    });

    it('rejects completely invalid token strings', async () => {
      const req = createRequest('/dashboard', 'not-a-jwt-token');
      await middleware(req);

      expect(mockRedirect).toHaveBeenCalled();
      expect(mockNext).not.toHaveBeenCalled();
    });

    it('rejects tokens with only two parts (missing signature)', async () => {
      const req = createRequest('/dashboard', 'header.payload');
      await middleware(req);

      expect(mockRedirect).toHaveBeenCalled();
      expect(mockNext).not.toHaveBeenCalled();
    });
  });

  describe('expired tokens', () => {
    it('rejects expired JWT tokens', async () => {
      const expiredToken = generateExpiredToken('user-123');
      await new Promise(resolve => setTimeout(resolve, 1100));

      const req = createRequest('/dashboard', expiredToken);
      await middleware(req);

      expect(mockRedirect).toHaveBeenCalled();
      expect(mockNext).not.toHaveBeenCalled();
    });
  });

  describe('invalid payload', () => {
    it('rejects tokens that have no userId in payload', async () => {
      const token = generateTokenWithoutUserId();
      const req = createRequest('/dashboard', token);
      await middleware(req);

      expect(mockRedirect).toHaveBeenCalled();
      expect(mockNext).not.toHaveBeenCalled();
    });
  });
});
